### ISSUE TITLE
A possible problem with read_dir function I noticed

### ISSUE THREAD

**Issue by patrickmorrell17** [cafltar/plfa_tools_aggregator#12]
When we have path_to_directory = pathlib.Path.cwd() / str(dir_path) / str(filename) (line 118) to pass to the read_file will this create a redundancy in the file path name since I said cwd() and we are assuming they are passing in the full file path? I was thinking of changing it to something like path_to_directory = pathlib.Path(str(dir_path) + '/' + str(filename)). It seemed to work fine with the test case but I feel it could cause problems with the __main__.py script. Let me know your thoughts! 
Thanks!

**Comment by bryanrcarlson** [comment]
Good catch. Yeah, no need for `pathlib.Path.cwd()` if we're assuming user is specifying absolute path to the directory. 

You may need to test, but I believe Pathlib is smart enough to use proper path separator for host OS when joining paths. So your code should look something like this (I changed name of variable from path_to_directory to be more accurate): `path_to_file = dir_path / str(filename)`. This prevents issues with manually adding the path separator since using the character '/' may not work if script is running on Windows (which uses '\'). Since dir_path is a Pathlib object, this should work, but you can use `joinpath()` if not.

**Comment by patrickmorrell17** [comment]
Ok, I'll make these changes and test it out! Thanks

**Comment by patrickmorrell17** [comment]
I made the changes and the tests all passed! I made a pull request for the read_dir branch.
